/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.kokumaji.explosivearrows

import kr.entree.spigradle.annotations.PluginMain
import org.bukkit.Bukkit
import org.bukkit.plugin.java.JavaPlugin

@PluginMain
class ExplosiveArrows: JavaPlugin() {

    companion object {
        lateinit var instance: ExplosiveArrows
    }

    override fun onLoad() {
        instance = this
        saveDefaultConfig()
    }

    override fun onEnable() {
        println("Plugin has been enabled!")
        Bukkit.getPluginManager().registerEvents(ArrowListener(), this)
        getCommand("arrows")?.setExecutor(CommandListener())
    }

}

