/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.kokumaji.explosivearrows

import kr.entree.spigradle.annotations.PluginMain
import org.bukkit.Bukkit
import org.bukkit.plugin.java.JavaPlugin

@PluginMain
class ExplosiveArrows: JavaPlugin() {

    // companion object is essentially 'static' in java
    companion object {
        lateinit var instance: ExplosiveArrows

        // can also have functions!
        fun getPrefix(color: Boolean): String {
            val prefix = "[${instance.name}]"

            return if(color) "§6$prefix§a" else prefix
        }
    }

    override fun onLoad() {
        instance = this
        saveDefaultConfig()
    }

    override fun onEnable() {
        println("${getPrefix(false)} Plugin has been enabled!")
        Bukkit.getPluginManager().registerEvents(ArrowListener(), this)
        getCommand("arrows")?.setExecutor(CommandListener())
    }

}

