/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.4.20"

    id("com.github.johnrengelman.shadow") version "6.1.0"
    id("kr.entree.spigradle") version "2.2.3"

}

version = "1.0"
var mainClassName = "com.kokumaji.explosivearrows.ExplosiveArrows"

repositories {
    maven(uri("https://repo.extendedclip.com/content/repositories/placeholderapi/"))
    maven(uri("https://jitpack.io"))
    maven(url = "https://repo.codemc.org/repository/maven-public/")

    jcenter()
    mavenCentral()

    maven(url = "https://papermc.io/repo/repository/maven-public/")


}

dependencies {
    // Align versions of all Kotlin components
    implementation(kotlin("stdlib"))
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:29.0-jre")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    compileOnly ("com.destroystokyo.paper:paper-api:1.16.5-R0.1-SNAPSHOT")

}

tasks {
    build {
        dependsOn("shadowJar")
    }

    shadowJar {
        archiveClassifier.set("")
    }

    spigot {
        name = "ExplosiveArrows"
        authors = mutableListOf("Kokumaji")
        apiVersion = "1.16"
        version = this.version

        commands {
            create("arrows") {
                usage = "/arrows"
            }
        }
    }
}
